### PR TITLE
chore: access key and secret key can be empty if role is used

### PR DESCRIPTION
**Pull request by shadracnicholas**

### CODE REVIEW

**Comment by TrayserCassa** [comment]
Why you want to leave them empty? They are required for Shopware to work

**Comment by shadracnicholas** [comment]
> Why you want to leave them empty? They are required for Shopware to work

No. [See](https://developer.shopware.com/docs/guides/hosting/infrastructure/filesystem.html#amazon-s3). It's also important when you want to use a role instead of the actual credentials when you deploy to AWS.

**Comment by TrayserCassa** [comment]
We use irsa service roles for aws so it's fine if this is empty. But we are missing then the serviceAccount in each deployment and also in the jobs.

**Comment by TrayserCassa** [comment]
And we need to remove the aws environment variables if they access and secret key is not set.

**Comment by TrayserCassa** [comment]
If the service account is not generated in the operator itself it should be passed through the crd. And if the crd has no service account we should not attach it at all.

**Review by TrayserCassa — APPROVED** [review]

**Pull request merged**
